name: deploy production UI

on:
  push:
    branches: 
      - main
    paths-ignore:
      - 'DAFrontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html/DAFrontend/admin
          pwd
          ls -la
          sudo git add .
          sudo git commit -m "serversideupdate"
          sudo git pull 
          sudo yarn
          sudo yarn run build
          pm2 ls 
          pm2 restart all
